os: linux
dist: trusty
sudo: false
language: lua

addons:
  apt:
    packages:
      - vim=2:7.4.052-1ubuntu3.1
      - lua5.1
      - lua-filesystem

install: true

before_script:
  - vim --version

script:
  - ./run-regressions --profiling --suite all
  - LUA_PATH='./test/lua-modules/?.lua' ./test/combine-profiles.lua ./test/output/*.profile

after_failure:
  - ./test/print-diffs.sh
