#! /usr/bin/env bash

if ! compgen 'test/output/*.profile' ; then
	echo "No profiles found!" >&2
	exit 1
fi

LUA_PATH='./test/lua-modules/?.lua' \
./test/combine-profiles.lua         \
    --output ./test/total.profile   \
    --coverage ./test/coverage.html \
    --                              \
    ./test/output/*.profile         ;
