#! /usr/bin/env bash

declare -x LUA_PATH='./test/lua-modules/?.lua'

declare -i profiling=0
declare -i done_suite=0
for arg ; do
	if [[ "${arg}" == '--profiling' ]] ; then
		(( profiling++ ))
	elif [[ "${arg}" == '--suite' ]] ; then
		(( done_suite++ ))
	elif [[ "${arg}" == '--help' || "${arg}" == '-h' ]] ; then
		cat <<-EOH
		./run-regressions
		    [--profiling]
		    [--suite SUITE]
		EOH
		exit 0
	fi
done

if (( ! done_suite )) ; then
	set -- "$@" --suite all
fi

if [[ -t 1 ]] ; then
	declare colours='--colours'
fi

set -e

./test/regressions.lua              \
    ${colours}                      \
    --testdir   ./test              \
    --vimrc     ./test/vimrc.vim    \
    "$@"                            ;

if (( profiling )) ; then
	./test/combine-profiles.lua         \
	    --output ./test/total.profile   \
	    --coverage ./test/coverage.html \
	    --                              \
	    ./test/output/*.profile         ;
fi

