#! /usr/bin/env bash

if (( $# == 0 )) ; then
	set -- --suite all
fi

if [[ -t 1 ]] ; then
	declare colours='--colours'
fi

./tests/regressions.lua            \
    ${colours}                     \
    --testdir   ./tests            \
    --vimrc     ./tests/vimrc.vim  \
    --suitefile ./tests/suites.cfg \
    "$@"
