#! /usr/bin/env bash
##############################################################################
# Check that all the "version" strings defined are consistent                #
##############################################################################

sedx () {
	sed                              \
	  --quiet                        \
	  --regexp-extended              \
	  --expression                   \
	  's/^.*'"$1"'.*$/\1/;TX;p;q;:X' \
	  "$2"                           ;
}

declare vers_readme=$(sedx 'Version: \*([^*]*)\*' README.markdown)

declare vers_plugin=$(sedx "let g:commentable_version\\s*=\\s*'([^']*)'" plugin/commentable.vim)

declare vers_comment=$(sedx 'VERSION:\s*(\S*)' plugin/commentable.vim)

declare vers_addon=$(jq --raw-output '.version' addon-info.json)

declare vers_doc=$(sedx 'VERSION:\s*(\S*)' doc/commentable.txt)

if [[ "${vers_readme}" != "${vers_plugin}"  ||
      "${vers_readme}" != "${vers_comment}" ||
      "${vers_readme}" != "${vers_addon}"   ||
      "${vers_readme}" != "${vers_doc}"     ]]
then
	cat >&2 <<-END_OF_ERROR
	Version do not match!
	    Readme        : |${vers_readme}|
	    Plugin        : |${vers_plugin}|
	    Comment       : |${vers_comment}|
	    Addon         : |${vers_addon}|
	    Documentation : |${vers_doc}|
	END_OF_ERROR
	exit 1
fi

exit 0
